name: ROS 2 Jazzy CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 配置 ROS 2 仓库
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: jazzy

    - name: 安装系统级与 ROS 2 依赖包 (补全行为树库)
      run: |
        sudo apt-get update
        #新增 ros-jazzy-behaviortree-cpp 
        sudo apt-get install -y libeigen3-dev cmake ros-jazzy-behaviortree-cpp
        
    - name: 编译安装 OSQP (二次规划核心)
      run: |
        git clone --recursive https://github.com/osqp/osqp.git
        cd osqp && mkdir build && cd build
        cmake .. && make && sudo make install
        sudo ldconfig

    - name: 编译安装 OsqpEigen (C++ 桥接库)
      run: |
        git clone https://github.com/robotology/osqp-eigen.git
        cd osqp-eigen && mkdir build && cd build
        cmake .. && make && sudo make install
        sudo ldconfig

    - name: 编译 ROS 2 项目 (包含外部消息包)
      run: |
        mkdir -p ros2_ws/src
        # 1. 把你的代码挂载进云端工作空间
        ln -s ${{ github.workspace }} ros2_ws/src/uav_inspection
        # 2. 让云端也去拉取 PX4 的外部字典包！！
        git clone https://github.com/PX4/px4_msgs.git ros2_ws/src/px4_msgs
        
        cd ros2_ws
        source /opt/ros/jazzy/setup.bash
        # 3. 全量编译！
        colcon build